### ISSUE TITLE
Filter Sets being used.

### ISSUE THREAD

**Issue by rbiswas4** [rbiswas4/calibrate_spectra#3]
I am worried that the filters that we have been using are not identical. Part of this is driven by the fact that in the example notebook, I show that the filters i, r of the set I am using don't have a complete overlap with the spectra. So doing the synthetic photometry to match to data which was done would not be possible, unless  there was a relaxed threshold of what level of non-overlap would be tolerated or something else I don't understand. The most likely reason is that there was a different set of filters being used.  And the photometry comparison we are doing is only good if the filters used are correct.

So, I think  it would be good to get the same set of filters in this study rather than rely on the set I was using. I think the easiest way of doing this is by adding a set of ascii files (one for each filter). The ascii files should have two columns the first representing wavelength (Angstrom would be great, but anything would do) and the second representing transmission probabilities (so the values should be a float in (0, 1) . It is probably best to add them to example_data directory in transientSources in a PR (or email works fine).

**Comment by nkarp** [comment]
Hi,

Here are my filters. Let me know if they are in the “wrong” format.

Also something I should have mention before. I allow my spectra to reach only 20% of the filter on the sides. For example for the V filter spectra can go only to 6200 and it will be ok. I hope you understand what I mean.  This freedom will be changes later.
Let me know if you have a question.
N

On 15 Aug 2015, at 18:05, rbiswas4 <notifications@github.com<mailto:notifications@github.com>> wrote:

I am worried that the filters that we have been using are not identical. Part of this is driven by the fact that in the example notebook, I show that the filters i, r of the set I am using don't have a complete overlap with the spectra. So doing the synthetic photometry to match to data which was done would not be possible, unless there was a relaxed threshold of what level of non-overlap would be tolerated or something else I don't understand. The most likely reason is that there was a different set of filters being used. And the photometry comparison we are doing is only good if the filters used are correct.

So, I think it would be good to get the same set of filters in this study rather than rely on the set I was using. I think the easiest way of doing this is by adding a set of ascii files (one for each filter). The ascii files should have two columns the first representing wavelength (Angstrom would be great, but anything would do) and the second representing transmission probabilities (so the values should be a float in (0, 1) . It is probably best to add them to example_data directory in transientSources in a PR (or email works fine).

�

**Comment by rbiswas4** [comment]
Sorry, did you forget to attach it or maybe attachments in replies to github do not work (maybe you need to email people directly?).

**Comment by rbiswas4** [comment]
Added the filter sets from Karpenka https://github.com/rbiswas4/calibrate_spectra/commit/b1c9dc8b5d6c683bc02a256d5478160aceae0e82
